name: On Pull Request Documentation Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: cnheider/postdoc@master

      - uses: actions/upload-artifact@v1    # Create an artifact of the html output.
        with:
          name: DocumentationHTML
          path: docs/_build/html/
